# DestinationRule resource handles how the destination should handle incoming traffic.
# In this manifest file, we are defining 'subsets' for each version of the service.
# Then, these subsets are getting used in virtual-services-canary.yaml file to route incoming traffic.
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: frontend
  namespace: blog-app
spec:
  host: frontend.blog-app.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: posts
  namespace: blog-app
spec:
  host: posts.blog-app.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: users
  namespace: blog-app
spec:
  host: users.blog-app.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: reviews
  namespace: blog-app
spec:
  host: reviews.blog-app.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: ratings
  namespace: blog-app
spec:
  host: ratings.blog-app.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2