---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-creds
  namespace: blog-app
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgAidQp2Zzuy4jnr8YsA2EgtCHwmoJIlY9jfmTEz2aTrP1fSY3hfa54om1opU+fCyPTe6NUKwG5ksvdXeRuJygKsx3Gt++E14eVN/SJ7IRQdlZh27DqomHxR3ls65SinG825Ya5Zz3Mm1nDH/rFKdipZ6WP6KEfQJIOiHOuTVgmWDMMHVsSLkiInUBlVRV1o5yOuVWSeOdJrUYy3oPJy1/cUS8qN1/kXIGL9eZlFjIIhYBEkRrgWcY/SrRTHesH8RoVu8o8XymzwpsJ0vnbcgFR3K+ei1NhTUQF0lRjxxMoxh/SrGjElCfkuojgO1Rq3Mq/ZF8iLnheAsbvgzELvoiw7+BQOw1sCrQQpCKZ4+iC/vHA6tPLdFiulBfH/2ZWdYoayP+bQsa9pPGbUZwVZmMUpdq9fvsdlJSKbDKpp6+fOlbZWeXznYq0wnQvO+FWXfSvNEOc2aEtq+rOfo0ksKSdmmel0u4rFPI1/JPxr6hLxglp1UBcoH8mHesg5px3NzTBD5cyrukA7L+mqLuRbtKMj5Q5tJMqJHl/bkCxEUnsGr9vJ7t2AfZ+KORPp47Kg8F1huCoy4fi7rIB3i4WHu+75aq0Jdw7gSTU3CzrHgM2hHZf1ukWd2CXfq7p3N13aPVK9faCed9s/mDonN/TLXQv0L7YIar9gLNLu7NfUA7aBg47JDiKRQQbAP4sYRn4B+bp9eftAOZ9ubNFMqMNC
    MONGO_INITDB_ROOT_USERNAME: AgAxgdCW/Tzc3KTrASdANg5Omsh+Vm0UJ5oqBieQw7PVoJ09C/KBq0xVbdxXPH/mNVhNBh+6WbNNodX9u8v+iYTf0C57gaXhsj13FqI9kIgaxvXKFBOYK/rRc0yTr0WM+40WqeWd+ykChpMvoLAMMHbCSh1H79Zrb3c2fZFiCTu4h1EGWQrQ57qLNKGLFksAfKHuDQy2+57UGuhESMA5pssYlG4YMuOIVZpsP7L/sHfeMtDH1UvXUdWzdp4h+P8EWRCPPxOov9IWRZ8UjNlYBuZRhp/vUHc9S3sgh5tn6l/RDckxZrpXoxbsJbLPhv5Bdb9O9tSBLC7Uv2P+2a/l1CsMajBkuqe/EtAAxtHa+cN117lbnqFMQXwoNz+kkNoUL4CAY7tpplz3GdPTmSx7DzXKRX6NK0gnmWk1xf3M+c2Lw2Hziv/uAY2rDdYSMszVzGfKmV/iT/TMdrxjqHUbbP/ozUG7azuT3HZv1IOQkXOTQ9h/yPPidofz+JQV/QyZTSyFAiS1VlKGWSmHXmGWwu+Ryhby/zi6GbFVIzisqxOvNaimHw0cY36sHHI/xH57P0K+yvfSYp6T5EH51KPwo6pNFAvOMGGfPnynEoDIRF/gdIlGTC4Je376NOKI0xxDV9U/jrChlOsCCqTyb1TIvF8oREIUmGUS877n6aTjKkH8osjQy/2+3cqjPmoIikdbzp96rIMGBucshkI=
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-creds
      namespace: blog-app
