---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-creds
  namespace: blog-app
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgBpDUZ3z5ewCikcbxEfL/X3XCMC/i9ZBV0D8DzCOviP92yhRXFcbx50P4Eji8AyXNlqD+rfh/2onFxCUzVr/Ja4ik6elnqW8t3rjJHrRkW02pnloXc7ue3Lp/Lx6euh+d80tYKHLsIEr9yuDC1vyu6r6T8cQBCikycLBN8eJdvwLZIjEMe71c4QGbTOHzhjO3zKse3R8SHwhHd/Km3flljoq3h3x55WKI0VL/MsZejXa6MlydfsuOLseXin5n0qY+o2W69Ojn9WXvgEYUuvm68hfY4OjHEE32EeQfApOQkiGcjk99fHNLZVRlOj9dI3IIB2njWWmNkUg/uqevxZaUI+iObswb1HtV38Sr5za1qi5fb96J4NtEklIdNG/wOT3RcM/7sGIanMoEO6uxHRPTS0XTuBN1qzqutacjEivXqtPR5FNY1lhP3jEbGGsRNXN/2agRtx0nNSvrbmOwtC4lLj1igD0Bt4uLeg77Vnp2zZXg+AXV+u8sBKsnJcLjiTG6MD4+kIq1CjsG3IaOjzL3zzsQbkCTpjAW0AcF1UObZtZdQy0hCq4TIFMTbPhH+6azZIX0eFHPkdlK+XXBUhDMGAiVvvAEdFb0msfT6geO9HUv80FDkG+PppggeFpbF4XINMtWDtSbB0cTBM1uu2sKCpWFoME5QwelcoB4wlC+hi/4zk0JfVnUHEFqNOcFuRssvTba1Z/EielD8=
    MONGO_INITDB_ROOT_USERNAME: AgDD4po8QfTfkOs5WhuwXUDjeCSTc3aLJezvw1CX9FonLcJgnFFC0jViYaeTpulFiMPUszANECC7kt26BUfUstx4ZxRfXqcpMoUmYKuDWukQNBqm8r3ahfoVRn5IW8sfNC1iDel+ma5M08uqPxN+wy+RAJ4sMj6HGBGa77RVkXERA5/XWl8YC0LSdvB3+J1RZ+qBiC5+rziIiL1k73xqFXj2Suv9RhuTZ4ehfkHPz0GXaympoBLOAI4GdGmUkFTs8RwBS8KtkxfyXxwGRFZ6BaT8ijp78Y9RPmHdR28mcY4SFENYa819UuMS6NuRQyPdoFZmdkg0igX2gYJTZrcSWbp8ylHxElWM5fPls+uPUJIJ0d6+eE0kGmQLgvPDrHPmxMIXAH2tsM0xgr75LZT/AopVsIvbGCrF2AA+FlaSxTHybDKMYnOyhG28wKmzV9e2Gc9dj/w4QEwlea6dgaJIksZMi/vn9AOL+O9bZIQS/qJcv8nEzTL1QREibWBe2Vc9aio2vzCJ8FBkjHyI0P3TxG33M6Qa31tNO/2PPMn5j4xT9JpOgq60zoz4quANgJBFwdmQvbSHeHjdXD9TvbKIr5qUSgQry5T9CHX8U1kyVHofWta05Jt4bv8XJT4cecIg0Rz/wGaHFELdSSerLebEzlcgyt3qaGU7T/VF7nyUM7vLa0PGa6kreD+RdaTerrIqxbuCZzYv
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-creds
      namespace: blog-app
