---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-creds
  namespace: blog-app
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgAxexzKSzE97vXhV+YUj0gfX/KCaG+Fx3oB9eDPmCq1R3XXces+selneVvaVTKBSIoIw/Y26I2d0Mlpd97tyvHMhC1mNerYU2PmNWI4QjztBkRFzjJ+pgIUk6PpUyjof6UgN4Z4vyUdMLBFtWKt4kFm3YGYbtutjTYfk4uCYshm5Ouq+b8+0O+9y0AnKxyy7hkJA6uw+7YUph74m+7x+Hwsk7oLIP0ZTKB4HgapmTaygAZTGEuqzBTFoCFVQdnpgEs2H4T4y00kYpKTT96w39Of9gmWdKAhhjaOLuQJZc+Gmhd59W6c/0yrfmO43PtrMGhzVwECjpH7bQqci7m0YoJNmeGfG3L+rmBBNH43jsZm2DZLiDR56+wNuJ9mvyUnykvB/+7LuqN00brpTfgjC5xvROksEBUyGqErZjhQaZCJLJe2Oo2KD/a6LGBHOtseINpJ2+qITDSlqb+U10r198McmFd0NYy5wBKKoyhe4yFAh9uSWHvLi85+oddNCgg5wGwrEFgeRVhF0Bmg2v2z7Nasmhur3qm25InkywIr7YnTrRzFkxUhPTyD/My9QJZfiemau8aWZhH1+C4XDtkd26h2Iauo1n/IfUFTZgCG4kgQYIPainNzNhjUx4ppWuKMMIvlaqwXI+Kt2/1DM90X+949A8qnq7o3f4QpVIeT0mKxLc2hQqlaQcTbI9XvegWuNwk1T1wIJwhVckt8zApR
    MONGO_INITDB_ROOT_USERNAME: AgBwFwRDZF6uzNtxxzPxKVM49F8dqG8rZvPxHGKKiJHDZDwJes5jXd9BnVImKeOuLwgb9jo65Oh2Ly52epMdr1GeG0yStr2nDpAUn1CBvZkxLIwpXN2xiHA0R0bU7WGVOVsnJURwTj0hE+Eo+yyNoWTtGIPFqzWBrifRGhVxfv+MIpIxHwLajFHLMv1GMalN08CZEPtz6wVbmaU330f0KUUebTNdAdnkSPNp5ZvklHTmC7Fz55POb/731J3+6O0+eoqoz5jKQMlgAe+WkM2p9h7LEcRvKgnBfGICWMnahQ9oTV6rdieiiKnh2ZXmArP6yNlfH5fIjUzxJMntE+ClGMs4PUgt/azTa6qEoCcYU4EKMAPHSwiDdoHZLD55yT0x4mxBRMWKWN6bkKEeC5VDRhZMMHWAkop8hdW4FMbKNMjKzLeRRMUOR4Dg9PvODezCKnw50fhG0ZPQCY+6+MfJsbVRzodw7Z/0zZFkMsP/0KGEN+SYCeE9a3c0vsYel7cfmc6tha1bcZ/k+ZGy74yhJbLpNOtVMogg6Ir4nHtIF9/Rv0SkMl0SQGR5DmSFWhHrAKAXnv0BeBD6yHPNlpHvgwqevdn8A/JQ98vy1lIZMzjofgZBtaM2zasXcbSsG+3Zcf88Ig1MRFEdXhctuKv2R36U+V7eq/hTkUOENffbnEiKia8KKvld0r4asn4lX7BNd1C3jU1l
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-creds
      namespace: blog-app
