---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-creds
  namespace: blog-app
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgAfhMlP85gWROiJyiQ1763tbAaFluayOcb8aMLhZ08KSxb+ZisrVWMVnDSJY1ep9M5sj9XzywZC/zfeXomlq/cxbbm4vpYSxN8X1go1NcsGmUUTVGo8ckL/f92XnHfKJDCzMCJYZxEWujqaQvg1zlkyteJ789APgPoaivvJAOWVyRQhAsKh0+sX3FSiMdpNO2/V7+Lb7f42inrKGk6zyIj6Ij9wNkrQLbUTTbEoOHh7s6QIyvOdQk9nDFS0w3cpKIZv5g2HyUJwrMBbR0dSG0Z7aQ8O0hKiZVMiVo5n9Pz3AJ2+22Pk9PXvsosqiR3apr+TK5zNIhHQ3O974SoPHKG/bdsiwH5y4pY+Czunt8/BXSWjQpF3ZshVF3vSsf4xKe7CjPg1tPw8NxD1lIeNoTpAY9/EY+ZH4hMQGtygWqtr/wfugoq/Zpux7B1ndnEwFRaiU78M+7te9U3igfrnbvQA8CUvPsjsa0rjigp7yotQqCZH77oXJESevytrbm9iEQy9S3IpcOvr7ATIwrCpFGsKjah0SgnN8ta6+gpc/+dbFCsW0j9p+GQ39MHPILtwZVJEie1BzCcmI7TzgsRXACe96XD4Bhvo3iXAEPIi8v/24HoouHh21JOwH1lZdQRA/caEC2uK6mxJ6JLt3SJji9GDowYixH/2Qh3CiWHIkPRvGJ1c4SCV9kM/y0dvTclqfdKlLLAIGIHN11ag
    MONGO_INITDB_ROOT_USERNAME: AgB0U6XL28VbzL6HbWF1lSF+VP8mKP++btdE3WjhfqyoqpVersDWobgZovOzjVAfbpRJNogBZKUqM34oz975FCmamr67qQL7JuyJWWwURmOwiuNsQlg1/2/2p2Dl9GkTpnfzPIWaqBMEzoVmOP6zZSX0SRmtibJvAxqML/HrWsY6/MD295QpIZ9HSh0og+zIR0EICnPbNAQv5llRZ8h0eU0LOxAl9TlnggmNm7KifwCYyassRwSLGB4pP3KTkMs8VTXULzRcqEMHzmoRs7tJDsHPrn1MfEa5lnxYudD9rhaIOpkIc4mwhmGQc8v3AiuQZ36BLauZda5lkL6JReOaHGGteegXcWD+DILyy+iVarTJOXG7dR82ZZT378P3yJuIcmghhYEvaerSySs4HNHB+rm4gzgxt7YSQ1nBmhya59wm1rOuay/5hHOTMjxLT+UV1qixnbP22LScU0M2MUaLWKH2n+aFbepeLTp1syexUkDuYQbEQng088D/QK9sp0ZRe2bpq/OcxbaHOP2JzmybBQOna1rCqE4daNJ0yAECw+XAl7sBUQvggrhCrl/xOWEjwDprL5b/89DsTcO6QeIG7OSWxDs6T8WUCUmyk1ngvDvi2ujoTOuhEhKrrG6ueg9TD2mBHA4eYV0G7Zei21Ilogn3rhuDiYpdH0wnqVOx+SsaFoNRLskltturZHJcAQGmTiK3WrVS
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-creds
      namespace: blog-app
