apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-apps
  # ApplicationSet resource will be deployed to argocd namespace,
  # not the applications which will argocd manage.
  # Each application will define which namespace they will be located in
  # within their respective manifest files.
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/tunacinsoy/sba-environments.git
      revision: HEAD
      directories:
      - path: manifests/*
      # We do not want argocd to manage itself
      - path: manifests/argocd
        exclude: true
  template:
    metadata:
    # Application name will be the folder name, for instance 'sealed-secrets'
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/tunacinsoy/sba-environments.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          selfHeal: true
