apiVersion: external-secrets.io/v1beta1
# SecretStore is better for isolation compared to ClusterSecretStore, however let's stick with this one for the example
kind: ClusterSecretStore
metadata:
  name: gcp-backend
  namespace: blog-app
spec:
  provider:
      gcpsm:
        auth:
          secretRef:
            secretAccessKeySecretRef:
              name: gcpsm-secret
              key: secret-access-credentials
              namespace: default
        # Will be modified with the project ID credentials during workflow
        projectID: PROJECT_ID_PH