# In order to access the secret that is located in gcp secret manager,
# We created a service account within gcp, and the following secret resource
# will have that service account credentials.
# After then, ClusterSecretStore type of resource will use that secret resource, and
# retrieve the secrets located in gcp secrets manager.


apiVersion: v1
data:
  # Will be modified with the service account credentials during workflow
  secret-access-credentials: SECRET_ACCESS_CREDS_PH
kind: Secret
metadata:
  name: gcpsm-secret
# An Opaque secret is a generic secret type that can store arbitrary key-value pairs.
# The keys in the data field can be any string, and the corresponding values are base64-encoded strings.
# This type is commonly used when you need to store configuration data, credentials, or other sensitive information that doesn’t fit into the predefined secret types.
type: Opaque
---
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: gcp-backend
spec:
  provider:
      gcpsm:
        auth:
          secretRef:
            secretAccessKeySecretRef:
              name: gcpsm-secret
              key: secret-access-credentials
              namespace: default
        # Will be modified with the project ID credentials during workflow
        projectID: PROJECT_ID_PH