apiVersion: external-secrets.io/v1beta1
# SecretStore is better for isolation compared to ClusterSecretStore
kind: ClusterSecretStore
metadata:
  name: gcp-backend
  #namespace: blog-app
spec:
  provider:
      gcpsm:
        auth:
          secretRef:
            secretAccessKeySecretRef:
              name: gcpsm-secret
              key: secret-access-credentials
              #namespace: blog-app
        # Will be modified with the project ID credentials during workflow
        projectID: PROJECT_ID_PH