name: Dev Env Continuous Deployment Workflow
on:
  push:
    branches: [ dev ]
jobs:
  create-environment-and-deploy-app:
    name: Create Environment and Deploy the Application
    uses: ./.github/workflows/create-cluster.yml
    secrets: inherit
  run-tests:
    name: Run Integration Tests
    needs: [create-environment-and-deploy-app]
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
  format-images:
    name: Format Images into SHA256 Digest Format
    needs: [run-tests]
    uses: ./.github/workflows/format-images.yml
    secrets: inherit
  binary-auth:
    name: Attest Images
    needs: [format-images]
    uses: ./.github/workflows/attest-images.yml
    secrets: inherit
  raise-pull-request:
    name: Raise PR to Prod Branch
    needs: [binary-auth]
    uses: ./.github/workflows/raise-pr.yml
    secrets: inherit