name: Dev Env Continuous Deployment Workflow
on:
  push:
    branches: [ dev ]
jobs:
  create-environment-and-deploy-app:
    name: Create Environment and Deploy the Application
    uses: ./.github/workflows/create-cluster.yml
    secrets: inherit
  run-tests:
    name: Run Integration Tests
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
  binary-auth:
    name: Attest Images
    uses: ./.github/workflows/attest-images.yml
    secrets: inherit
  # raise-pull-request:
  #   name: Raise PR to prod branch
  #   uses: ./.github/workflows/raise-pr.yml
  #   secrets: inherit