name: Format Images into SHA256 Digest
on: [workflow_call]
jobs:
  format-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Run Bash Script
        working-directory: ./scripts
        run: |
          chmod +x convert-images-into-sha256-format.sh
          ./convert-images-into-sha256-format.sh
