name: Run Integration Tests
on: [workflow_call]
jobs:
  test-application:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests
    steps:
    # checkout@v4 is the latest version
    - uses: actions/checkout@v4
    - name: Extract branch name
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    - id: gcloud-auth
      name: Authenticate with gcloud
      # auth@v2 is the latest version
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    - name: Set up Cloud SDK
      id: setup-gcloud-sdk
      # setup-gcloud@v2 is the latest version
      uses: 'google-github-actions/setup-gcloud@v2'
    - name: Get kubectl credentials
      id: 'get-credentials'
      # get-gke-credentials@v2 is the latest version
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: sba-cluster-${{ steps.extract_branch.outputs.branch }}
        location: ${{ secrets.CLUSTER_LOCATION }}
    - name: Compute Application URL
      id: compute-application-url
      # We stopped using frontend svc as LoadBalancer after we deployed istio-ingress, so we need to update the command
      run: external_ip=$(kubectl get svc istio-ingress -n istio-ingress --output jsonpath='{.status.loadBalancer.ingress[0].ip}') && echo ${external_ip} && sed -i "s/localhost/${external_ip}/g" integration-test.py
    - id: run-integration-test
      name: Run Integration Test
      run: python3 integration-test.py